# autogenerated from opcodes_base.dat, DO NOT EDIT!

from hardware.cpu import CPUTrapInvalidOP

from hardware.Z80.tools import *

from tables import *


class Z80MixinBASE(object):
    def op_00(self):
        """ NOP """
        self.icount -= 4; self.itotal += 4
        # NOP
        pass
        # end
    
    def op_01(self):
        """ LD BC,@ """
        self.icount -= 10; self.itotal += 10
        # LD
        self.bc = self.read_op_arg16()
        # end
    
    def op_02(self):
        """ LD (BC),A """
        self.icount -= 7; self.itotal += 7
        # LD
        self.write(self.bc, self.a)
        # end
    
    def op_06(self):
        """ LD B,# """
        self.icount -= 7; self.itotal += 7
        # LD
        self.b = self.read_op()
        # end
    
    def op_0A(self):
        """ LD A,(BC) """
        self.icount -= 7; self.itotal += 7
        # LD
        self.a = self.read(self.a)
        # end
    
    def op_0E(self):
        """ LD C,# """
        self.icount -= 7; self.itotal += 7
        # LD
        self.c = self.read_op()
        # end
    
    def op_11(self):
        """ LD DE,@ """
        self.icount -= 10; self.itotal += 10
        # LD
        self.de = self.read_op_arg16()
        # end
    
    def op_12(self):
        """ LD (DE),A """
        self.icount -= 7; self.itotal += 7
        # LD
        self.write(self.de, self.a)
        # end
    
    def op_16(self):
        """ LD D,# """
        self.icount -= 7; self.itotal += 7
        # LD
        self.d = self.read_op()
        # end
    
    def op_1A(self):
        """ LD A,(DE) """
        self.icount -= 7; self.itotal += 7
        # LD
        self.a = self.read(self.a)
        # end
    
    def op_1E(self):
        """ LD E,# """
        self.icount -= 7; self.itotal += 7
        # LD
        self.e = self.read_op()
        # end
    
    def op_21(self):
        """ LD HL,@ """
        self.icount -= 10; self.itotal += 10
        # LD
        self.hl = self.read_op_arg16()
        # end
    
    def op_22(self):
        """ LD (@),HL """
        self.icount -= 16; self.itotal += 16
        # LD
        self.write16(self.read_op_arg16(), self.hl)
        # end
    
    def op_26(self):
        """ LD H,# """
        self.icount -= 7; self.itotal += 7
        # LD
        self.h = self.read_op()
        # end
    
    def op_2A(self):
        """ LD HL,(@) """
        self.icount -= 16; self.itotal += 16
        # LD
        self.hl = self.read16(self.read_op_arg16())
        # end
    
    def op_2E(self):
        """ LD L,# """
        self.icount -= 7; self.itotal += 7
        # LD
        self.l = self.read_op()
        # end
    
    def op_31(self):
        """ LD SP,@ """
        self.icount -= 10; self.itotal += 10
        # LD
        self.sp = self.read_op_arg16()
        # end
    
    def op_32(self):
        """ LD (@),A """
        self.icount -= 13; self.itotal += 13
        # LD
        self.write(self.read_op_arg16(), self.a)
        # end
    
    def op_36(self):
        """ LD (HL),# """
        self.icount -= 10; self.itotal += 10
        # LD
        self.write(self.hl, self.read_op_arg())
        # end
    
    def op_3A(self):
        """ LD A,(@) """
        self.icount -= 13; self.itotal += 13
        # LD
        self.a = self.read(self.read_op_arg16())
        # end
    
    def op_3E(self):
        """ LD A,# """
        self.icount -= 7; self.itotal += 7
        # LD
        self.a = self.read_op()
        # end
    
    def op_40(self):
        """ LD B,B """
        self.icount -= 4; self.itotal += 4
        # LD
        pass
        # end
    
    def op_41(self):
        """ LD B,C """
        self.icount -= 4; self.itotal += 4
        # LD
        self.b = self.c
        # end
    
    def op_42(self):
        """ LD B,D """
        self.icount -= 4; self.itotal += 4
        # LD
        self.b = self.d
        # end
    
    def op_43(self):
        """ LD B,E """
        self.icount -= 4; self.itotal += 4
        # LD
        self.b = self.e
        # end
    
    def op_44(self):
        """ LD B,H """
        self.icount -= 4; self.itotal += 4
        # LD
        self.b = self.h
        # end
    
    def op_45(self):
        """ LD B,L """
        self.icount -= 4; self.itotal += 4
        # LD
        self.b = self.l
        # end
    
    def op_46(self):
        """ LD B,(HL) """
        self.icount -= 7; self.itotal += 7
        # LD
        self.b = self.read(self.b)
        # end
    
    def op_47(self):
        """ LD B,A """
        self.icount -= 4; self.itotal += 4
        # LD
        self.b = self.a
        # end
    
    def op_48(self):
        """ LD C,B """
        self.icount -= 4; self.itotal += 4
        # LD
        self.c = self.b
        # end
    
    def op_49(self):
        """ LD C,C """
        self.icount -= 4; self.itotal += 4
        # LD
        pass
        # end
    
    def op_4A(self):
        """ LD C,D """
        self.icount -= 4; self.itotal += 4
        # LD
        self.c = self.d
        # end
    
    def op_4B(self):
        """ LD C,E """
        self.icount -= 4; self.itotal += 4
        # LD
        self.c = self.e
        # end
    
    def op_4C(self):
        """ LD C,H """
        self.icount -= 4; self.itotal += 4
        # LD
        self.c = self.h
        # end
    
    def op_4D(self):
        """ LD C,L """
        self.icount -= 4; self.itotal += 4
        # LD
        self.c = self.l
        # end
    
    def op_4E(self):
        """ LD C,(HL) """
        self.icount -= 7; self.itotal += 7
        # LD
        self.c = self.read(self.c)
        # end
    
    def op_4F(self):
        """ LD C,A """
        self.icount -= 4; self.itotal += 4
        # LD
        self.c = self.a
        # end
    
    def op_50(self):
        """ LD D,B """
        self.icount -= 4; self.itotal += 4
        # LD
        self.d = self.b
        # end
    
    def op_51(self):
        """ LD D,C """
        self.icount -= 4; self.itotal += 4
        # LD
        self.d = self.c
        # end
    
    def op_52(self):
        """ LD D,D """
        self.icount -= 4; self.itotal += 4
        # LD
        pass
        # end
    
    def op_53(self):
        """ LD D,E """
        self.icount -= 4; self.itotal += 4
        # LD
        self.d = self.e
        # end
    
    def op_54(self):
        """ LD D,H """
        self.icount -= 4; self.itotal += 4
        # LD
        self.d = self.h
        # end
    
    def op_55(self):
        """ LD D,L """
        self.icount -= 4; self.itotal += 4
        # LD
        self.d = self.l
        # end
    
    def op_56(self):
        """ LD D,(HL) """
        self.icount -= 7; self.itotal += 7
        # LD
        self.d = self.read(self.d)
        # end
    
    def op_57(self):
        """ LD D,A """
        self.icount -= 4; self.itotal += 4
        # LD
        self.d = self.a
        # end
    
    def op_58(self):
        """ LD E,B """
        self.icount -= 4; self.itotal += 4
        # LD
        self.e = self.b
        # end
    
    def op_59(self):
        """ LD E,C """
        self.icount -= 4; self.itotal += 4
        # LD
        self.e = self.c
        # end
    
    def op_5A(self):
        """ LD E,D """
        self.icount -= 4; self.itotal += 4
        # LD
        self.e = self.d
        # end
    
    def op_5B(self):
        """ LD E,E """
        self.icount -= 4; self.itotal += 4
        # LD
        pass
        # end
    
    def op_5C(self):
        """ LD E,H """
        self.icount -= 4; self.itotal += 4
        # LD
        self.e = self.h
        # end
    
    def op_5D(self):
        """ LD E,L """
        self.icount -= 4; self.itotal += 4
        # LD
        self.e = self.l
        # end
    
    def op_5E(self):
        """ LD E,(HL) """
        self.icount -= 7; self.itotal += 7
        # LD
        self.e = self.read(self.e)
        # end
    
    def op_5F(self):
        """ LD E,A """
        self.icount -= 4; self.itotal += 4
        # LD
        self.e = self.a
        # end
    
    def op_60(self):
        """ LD H,B """
        self.icount -= 4; self.itotal += 4
        # LD
        self.h = self.b
        # end
    
    def op_61(self):
        """ LD H,C """
        self.icount -= 4; self.itotal += 4
        # LD
        self.h = self.c
        # end
    
    def op_62(self):
        """ LD H,D """
        self.icount -= 4; self.itotal += 4
        # LD
        self.h = self.d
        # end
    
    def op_63(self):
        """ LD H,E """
        self.icount -= 4; self.itotal += 4
        # LD
        self.h = self.e
        # end
    
    def op_64(self):
        """ LD H,H """
        self.icount -= 4; self.itotal += 4
        # LD
        pass
        # end
    
    def op_65(self):
        """ LD H,L """
        self.icount -= 4; self.itotal += 4
        # LD
        self.h = self.l
        # end
    
    def op_66(self):
        """ LD H,(HL) """
        self.icount -= 7; self.itotal += 7
        # LD
        self.h = self.read(self.h)
        # end
    
    def op_67(self):
        """ LD H,A """
        self.icount -= 4; self.itotal += 4
        # LD
        self.h = self.a
        # end
    
    def op_68(self):
        """ LD L,B """
        self.icount -= 4; self.itotal += 4
        # LD
        self.l = self.b
        # end
    
    def op_69(self):
        """ LD L,C """
        self.icount -= 4; self.itotal += 4
        # LD
        self.l = self.c
        # end
    
    def op_6A(self):
        """ LD L,D """
        self.icount -= 4; self.itotal += 4
        # LD
        self.l = self.d
        # end
    
    def op_6B(self):
        """ LD L,E """
        self.icount -= 4; self.itotal += 4
        # LD
        self.l = self.e
        # end
    
    def op_6C(self):
        """ LD L,H """
        self.icount -= 4; self.itotal += 4
        # LD
        self.l = self.h
        # end
    
    def op_6D(self):
        """ LD L,L """
        self.icount -= 4; self.itotal += 4
        # LD
        pass
        # end
    
    def op_6E(self):
        """ LD L,(HL) """
        self.icount -= 7; self.itotal += 7
        # LD
        self.l = self.read(self.l)
        # end
    
    def op_6F(self):
        """ LD L,A """
        self.icount -= 4; self.itotal += 4
        # LD
        self.l = self.a
        # end
    
    def op_70(self):
        """ LD (HL),B """
        self.icount -= 7; self.itotal += 7
        # LD
        self.write(self.hl, self.b)
        # end
    
    def op_71(self):
        """ LD (HL),C """
        self.icount -= 7; self.itotal += 7
        # LD
        self.write(self.hl, self.c)
        # end
    
    def op_72(self):
        """ LD (HL),D """
        self.icount -= 7; self.itotal += 7
        # LD
        self.write(self.hl, self.d)
        # end
    
    def op_73(self):
        """ LD (HL),E """
        self.icount -= 7; self.itotal += 7
        # LD
        self.write(self.hl, self.e)
        # end
    
    def op_74(self):
        """ LD (HL),H """
        self.icount -= 7; self.itotal += 7
        # LD
        self.write(self.hl, self.h)
        # end
    
    def op_75(self):
        """ LD (HL),L """
        self.icount -= 7; self.itotal += 7
        # LD
        self.write(self.hl, self.l)
        # end
    
    def op_77(self):
        """ LD (HL),A """
        self.icount -= 7; self.itotal += 7
        # LD
        self.write(self.hl, self.a)
        # end
    
    def op_78(self):
        """ LD A,B """
        self.icount -= 4; self.itotal += 4
        # LD
        self.a = self.b
        # end
    
    def op_79(self):
        """ LD A,C """
        self.icount -= 4; self.itotal += 4
        # LD
        self.a = self.c
        # end
    
    def op_7A(self):
        """ LD A,D """
        self.icount -= 4; self.itotal += 4
        # LD
        self.a = self.d
        # end
    
    def op_7B(self):
        """ LD A,E """
        self.icount -= 4; self.itotal += 4
        # LD
        self.a = self.e
        # end
    
    def op_7C(self):
        """ LD A,H """
        self.icount -= 4; self.itotal += 4
        # LD
        self.a = self.h
        # end
    
    def op_7D(self):
        """ LD A,L """
        self.icount -= 4; self.itotal += 4
        # LD
        self.a = self.l
        # end
    
    def op_7E(self):
        """ LD A,(HL) """
        self.icount -= 7; self.itotal += 7
        # LD
        self.a = self.read(self.a)
        # end
    
    def op_7F(self):
        """ LD A,A """
        self.icount -= 4; self.itotal += 4
        # LD
        pass
        # end
    
    def op_F9(self):
        """ LD SP,HL """
        self.icount -= 6; self.itotal += 6
        # LD
        self.sp = self.hl
        # end
    
    def _init_base(self):
        """ init tables """
        self._base = [self._invalid] * 0x100
        self._base[0x00] = self.op_00 # NOP
        self._base[0x01] = self.op_01 # LD BC,@
        self._base[0x02] = self.op_02 # LD (BC),A
        self._base[0x06] = self.op_06 # LD B,#
        self._base[0x0A] = self.op_0A # LD A,(BC)
        self._base[0x0E] = self.op_0E # LD C,#
        self._base[0x11] = self.op_11 # LD DE,@
        self._base[0x12] = self.op_12 # LD (DE),A
        self._base[0x16] = self.op_16 # LD D,#
        self._base[0x1A] = self.op_1A # LD A,(DE)
        self._base[0x1E] = self.op_1E # LD E,#
        self._base[0x21] = self.op_21 # LD HL,@
        self._base[0x22] = self.op_22 # LD (@),HL
        self._base[0x26] = self.op_26 # LD H,#
        self._base[0x2A] = self.op_2A # LD HL,(@)
        self._base[0x2E] = self.op_2E # LD L,#
        self._base[0x31] = self.op_31 # LD SP,@
        self._base[0x32] = self.op_32 # LD (@),A
        self._base[0x36] = self.op_36 # LD (HL),#
        self._base[0x3A] = self.op_3A # LD A,(@)
        self._base[0x3E] = self.op_3E # LD A,#
        self._base[0x40] = self.op_40 # LD B,B
        self._base[0x41] = self.op_41 # LD B,C
        self._base[0x42] = self.op_42 # LD B,D
        self._base[0x43] = self.op_43 # LD B,E
        self._base[0x44] = self.op_44 # LD B,H
        self._base[0x45] = self.op_45 # LD B,L
        self._base[0x46] = self.op_46 # LD B,(HL)
        self._base[0x47] = self.op_47 # LD B,A
        self._base[0x48] = self.op_48 # LD C,B
        self._base[0x49] = self.op_49 # LD C,C
        self._base[0x4A] = self.op_4A # LD C,D
        self._base[0x4B] = self.op_4B # LD C,E
        self._base[0x4C] = self.op_4C # LD C,H
        self._base[0x4D] = self.op_4D # LD C,L
        self._base[0x4E] = self.op_4E # LD C,(HL)
        self._base[0x4F] = self.op_4F # LD C,A
        self._base[0x50] = self.op_50 # LD D,B
        self._base[0x51] = self.op_51 # LD D,C
        self._base[0x52] = self.op_52 # LD D,D
        self._base[0x53] = self.op_53 # LD D,E
        self._base[0x54] = self.op_54 # LD D,H
        self._base[0x55] = self.op_55 # LD D,L
        self._base[0x56] = self.op_56 # LD D,(HL)
        self._base[0x57] = self.op_57 # LD D,A
        self._base[0x58] = self.op_58 # LD E,B
        self._base[0x59] = self.op_59 # LD E,C
        self._base[0x5A] = self.op_5A # LD E,D
        self._base[0x5B] = self.op_5B # LD E,E
        self._base[0x5C] = self.op_5C # LD E,H
        self._base[0x5D] = self.op_5D # LD E,L
        self._base[0x5E] = self.op_5E # LD E,(HL)
        self._base[0x5F] = self.op_5F # LD E,A
        self._base[0x60] = self.op_60 # LD H,B
        self._base[0x61] = self.op_61 # LD H,C
        self._base[0x62] = self.op_62 # LD H,D
        self._base[0x63] = self.op_63 # LD H,E
        self._base[0x64] = self.op_64 # LD H,H
        self._base[0x65] = self.op_65 # LD H,L
        self._base[0x66] = self.op_66 # LD H,(HL)
        self._base[0x67] = self.op_67 # LD H,A
        self._base[0x68] = self.op_68 # LD L,B
        self._base[0x69] = self.op_69 # LD L,C
        self._base[0x6A] = self.op_6A # LD L,D
        self._base[0x6B] = self.op_6B # LD L,E
        self._base[0x6C] = self.op_6C # LD L,H
        self._base[0x6D] = self.op_6D # LD L,L
        self._base[0x6E] = self.op_6E # LD L,(HL)
        self._base[0x6F] = self.op_6F # LD L,A
        self._base[0x70] = self.op_70 # LD (HL),B
        self._base[0x71] = self.op_71 # LD (HL),C
        self._base[0x72] = self.op_72 # LD (HL),D
        self._base[0x73] = self.op_73 # LD (HL),E
        self._base[0x74] = self.op_74 # LD (HL),H
        self._base[0x75] = self.op_75 # LD (HL),L
        self._base[0x77] = self.op_77 # LD (HL),A
        self._base[0x78] = self.op_78 # LD A,B
        self._base[0x79] = self.op_79 # LD A,C
        self._base[0x7A] = self.op_7A # LD A,D
        self._base[0x7B] = self.op_7B # LD A,E
        self._base[0x7C] = self.op_7C # LD A,H
        self._base[0x7D] = self.op_7D # LD A,L
        self._base[0x7E] = self.op_7E # LD A,(HL)
        self._base[0x7F] = self.op_7F # LD A,A
        self._base[0xF9] = self.op_F9 # LD SP,HL
        self._base = tuple(self._base)
