#!/bin/bash
if [ ! -d ./env ]; then
    /usr/bin/env virtualenv --python=python2.6 env
    if [ $? == 127 ]; then
        echo "easy_install virtualenv"
        exit 1
    fi
fi

echo 'Done'

if [ ! -f ./env/bin/pip ]; then
    echo "install pip..."
    source ./env/bin/activate
    ./env/bin/easy_install -U docutils
    ./env/bin/easy_install -U pip
    echo '... done'
else
    source ./env/bin/activate
fi


./env/bin/pip install -E env -r requirements.txt